### PR TITLE
Remove solr

### PR DESCRIPTION
**Pull request by smacfarlane**
This removes SOLR and Sunspot dependencies from feeder and removes badges from search results.

@teknofire  Ready for review

### CODE REVIEW

**Comment by teknofire** [comment]
Should make sure the webcam and radar items are not checked by default, as they will always show up on top

**Comment by smacfarlane** [comment]
That's an artifact of how they get imported from the live site, since the server doesn't present that information.  

It should be fixed in the seeds, but I would think that belongs in a separate PR.

**Comment by teknofire** [comment]
Oh yeah, that's right.  Those are set on the feed

**Comment by teknofire** [comment]
👍

**Pull request merged**
